In [1]:
import os
import torch
import pandas as pd
import time
from tqdm import tqdm
import pyarrow.parquet as pq
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import psutil

/projects/extern/kisski/kisski_tegami/dir.project/micromamba/envs/jupyter/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
BASE_PATH = "/mnt/vast-kisski/projects/kisski_tegami"
#BASE_PATH = "/scratch/usr/nimtsspi/"
INPUT_PATH = f"{BASE_PATH}/datasets/TG"
OUTPUT_PATH = f"{BASE_PATH}/datasets/TG/labels"

In [4]:
df = pd.read_parquet(f"{INPUT_PATH}/TG_unified2.parquet")
df

,channel_id,message,topic,message_id,char_len,language
0,1150106827,Not Glory crying about her mom taking away her...,Religion,cfa932a6-f24b-44e1-b08d-a102708877f6,75,en
1,1150106827,LMFAO,Religion,01589340-b09a-4953-a295-c06fec59f33a,5,ar
2,1150106827,"Oh boy, looks like all Mercy lhemeson ( Glory'...",Religion,d79f5f15-0371-431f-ad0c-0945b841acfa,138,en
3,1150106827,When glorilla tries to say it's not a victim. ...,Religion,f76b1d68-b78e-4527-b0b8-e8000d3d80d6,64,en
4,1150106827,Glory fucking a plunger cause no men wants her...,Religion,acf342a4-e276-4b56-8a61-947f57fe7557,70,en
...,...,...,...,...,...,...
44704264,1114979442,संयुक्त पूर्व परीक्षा गट क : 03 एप्रिल 2022 का...,Indian edu,3b945400-c64e-457d-97a2-f2f88fa0670d,162,hi
44704265,1114979442,@user join everyone,Indian edu,b1fd9da1-bce6-41d1-8cd5-3f22f0391c26,18,en
44704266,1114979442,Live @user:30 Topic : Strategy for Group C Exa...,Indian edu,d12c58cc-7794-4643-9638-3955152be4f7,126,en
44704267,1114979442,Live @user:00 Join & Share By Ritesh Sir,Indian edu,7a70b7a4-3244-4cc4-af23-9aacaf2ef8b8,86,en
44704268,1114979442,Today live on 06:00 PM ECONOMICS ANALYSIS COMB...,Indian edu,af91f62a-e4e8-420c-9e54-a7df76228170,125,en

In [ ]:
df.language.value_counts()
#

language
en     15195866
zh       853085
ja       300871
ru       180016
de       157818
         ...
lez           5
dsb           5
co            4
hif           3
dty           2
Name: count, Length: 176, dtype: int64

In [7]:
df1 = df[df.language == "en"]
df2 = df[df.language != "en"]

In [24]:
df1.to_parquet(f"{INPUT_PATH}/TG_unified.parquet")

In [23]:
for text in df1.sample(20).message.to_list():
    print(text)
    print("--------------------------------")

#Melbourneprotest #Assange #WikiLeaks 🆘 @user via
--------------------------------
Living in Dark Times: I Revolt, Therefore I Am!
--------------------------------
He’s got one too….real name of this German Jew of Polish heritage …Herschel Grynszpan…murdered the German diplomat Ernst vom Rath in Paris on 7th Nov 38…but hey, that’s worth a memorial stone, right ?
--------------------------------
Wednesday Night Hockey: New York Rangers @ Washington Capitals tonight at 7:30pm ET on TNT. Chicago Blackhawks @ Colorado Avalanche tonight at 10pm ET on TNT.
--------------------------------
Let reach 100 subscribers folks🙏🙏🙏🙏🙏🙏🙏
--------------------------------
Black Lives Matter movement is nominated for a Nobel Peace Prize
--------------------------------
`Painkillers are the 'Mute Notifications' option for the body. `#thoughts
--------------------------------
Hel・Bortglömda Tid Released by Dim Records Vinyl comes in clear Orange with 12 songs in their well known style and their home language. $ 24.99
--------------------------------
Candytopia Launches New Mobile App Featuring AR #NBGeek
--------------------------------
robinwho? Submitted April 20, 2022 at 02:57PM by T-rampis via reddit
--------------------------------
Talk about a complete double standard. 🙄 BBC Investigating Journalist Who Wrote “Hitler Was Right”
--------------------------------
“Death” one of 5 ways to lose at Chess, according to PGN standard ,
--------------------------------
FKA twigs Says She Made a New Album During Quarantine She spoke about her creative endeavors throughout the pandemic on the Grammy Museum’s Programs at Home series
--------------------------------
🔴 New Report Reveals How Ashley Biden's Diary Made Its Way to Project Veritas In case you missed it.
--------------------------------
Scaramucci surprised at lack of banking response to Coinbase listing
--------------------------------
👇App for Unlimited internet dropped @user @user @user @user @user @user
--------------------------------
So true /r/gamingmemes @user
--------------------------------
Not saying we bottomed btw, just saying that only retarded people buy high and sell low.
--------------------------------
Figured you guys would like my doorbell install.
--------------------------------
You gon die👀💀 @user
--------------------------------

In [ ]:
df = pd.read_parquet(f"{OUTPUT_PATH}/TG_lexbias.parquet")
df

df

                                    message_id  lexbias
0         dbf24d19-7707-4a68-b67d-b42ed3bb6a5e   biased
1         b774cefe-c1ce-430b-9dfa-a9f043fce69d  neutral
2         728e869e-08cc-4e17-8fbe-e72c09a4826e   biased
3         2a695885-7d21-4816-9d8d-e3f7ca6bbe63   biased
4         d11015b3-418a-40aa-ba5f-ca1dcc41f975   biased
...                                        ...      ...
44704264  e21d283c-4024-4067-b39c-df8270179c88  neutral
44704265  225ae2b1-d4b5-4847-97e4-3928bc0ac5a7  neutral
44704266  d8df9eb1-bd3d-4b27-a366-6135c1b6ca86  neutral
44704267  4cccfe72-6e47-4b84-8ffc-2c75417c502c  neutral
44704268  2eb90148-4d80-4fe9-8787-0f63133cf4d3  neutral

[17576034 rows x 2 columns]